name: Auto Deploy to CloudPanel

on:
  push:
    branches:
      - main  # Memastikan otomatisasi jalan saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 31.97.107.14 # <--- GANTI LANGSUNG DENGAN IP SERVER ANDA
          username: rsbaladhikahusada
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/rsbaladhikahusada/htdocs/www.rsbaladhikahusada.com
            git pull origin main
            npm install
            npm run build
            php artisan optimize  
